### ISSUE TITLE
Unsatisfied Link Using CTRE Phoenix (WPI_TalonSRX) calls

### ISSUE THREAD

**Issue by RocketRedNeck** [pjreiniger/SnobotSim#41]
Any hope of getting mocks for CTRE?

MoveForward

19:35:48.724 [RobotThread] FATAL com.snobot.simulator.Simulator - Unsatisfied link error.  This likely means that there is a native call in WpiLib or the NetworkTables libraries.  Please tell PJ so he can mock it out.

Error Message: java.lang.UnsatisfiedLinkError: com.ctre.phoenix.motorcontrol.can.MotControllerJNI.Set_4(JIDDI)V
java.lang.UnsatisfiedLinkError: com.ctre.phoenix.motorcontrol.can.MotControllerJNI.Set_4(JIDDI)V
        at com.ctre.phoenix.motorcontrol.can.MotControllerJNI.Set_4(Native Method) ~[ButtonMadness.jar:?]
        at com.ctre.phoenix.motorcontrol.can.BaseMotorController.set(BaseMotorController.java:156) ~[ButtonMadness.jar:?]
        at com.ctre.phoenix.motorcontrol.can.BaseMotorController.set(BaseMotorController.java:94) ~[ButtonMadness.jar:?]
        at com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX.set(WPI_TalonSRX.java:68) ~[ButtonMadness.jar:?]
        at com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX.set(WPI_TalonSRX.java:46) ~[ButtonMadness.jar:?]
        at frc.robot.DriveSubsystem.driveForward(DriveSubsystem.java:46) ~[ButtonMadness.jar:?]
        at frc.robot.MoveForward.execute(MoveForward.java:23) ~[ButtonMadness.jar:?]
        at edu.wpi.first.wpilibj.command.Command.run(Command.java:238) ~[ButtonMadness.jar:?]
        at edu.wpi.first.wpilibj.command.Scheduler.run(Scheduler.java:220) ~[ButtonMadness.jar:?]
        at frc.robot.Robot.teleopPeriodic(Robot.java:142) ~[ButtonMadness.jar:?]
        at edu.wpi.first.wpilibj.IterativeRobotBase.loopFunc(IterativeRobotBase.java:213) ~[ButtonMadness.jar:?]
        at edu.wpi.first.wpilibj.IterativeRobot.startCompetition(IterativeRobot.java:41) ~[ButtonMadness.jar:?]
        at com.snobot.simulator.robot_container.JavaRobotContainer.startCompetition(JavaRobotContainer.java:32) ~[snobot_sim_gui-0.11.0-all.jar:?]
        at com.snobot.simulator.Simulator$2.run(Simulator.java:318) [snobot_sim_gui-0.11.0-all.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by RocketRedNeck** [comment]
Already raised in Issue #23. Closing to avoid harassing the developer.

**Comment by pjreiniger** [comment]
Latest release might fix this. If you can wait for 2019 beta testing, this will be GREATLY improved

**Comment by RocketRedNeck** [comment]
Do you mean 2019-dev?
BTW, love what this allows my students to do. Minimal testing of basic setup and linkage. Was able to demonstrate the crazy nonsense that the button classes can cause with this: https://github.com/BitBucketsFRC4183/ButtonMadness
Start mashing buttons.
